//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeisonAdarme.BLL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.tblServicio = new HashSet<Servicio>();
        }
    
        public System.Guid GUID { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public string PushRegistrationId { get; set; }
    
        public virtual ICollection<Servicio> tblServicio { get; set; }
    }
}
