//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeisonAdarme.BLL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        public Empresa()
        {
            this.tblEmpleado = new HashSet<Empleado>();
            this.tblServicio = new HashSet<Servicio>();
            this.tblTipoServicio = new HashSet<TipoServicio>();
        }
    
        public System.Guid GUID { get; set; }
        public string IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string TokenUnico { get; set; }
        public string UrlImagen { get; set; }
        public string NumeroTelefono { get; set; }
        public string NumeroCelular { get; set; }
        public string Direccion { get; set; }
        public Nullable<decimal> Longitud { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Empleado> tblEmpleado { get; set; }
        public virtual Usuario tblUsuario { get; set; }
        public virtual ICollection<Servicio> tblServicio { get; set; }
        public virtual ICollection<TipoServicio> tblTipoServicio { get; set; }
    }
}
