//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeisonAdarme.BLL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadoServicio
    {
        public EstadoServicio()
        {
            this.tblServicio = new HashSet<Servicio>();
        }
    
        public int IdEstadoServicio { get; set; }
        public string NombreEstadoServicio { get; set; }
        public Nullable<bool> EsActivo { get; set; }
    
        public virtual ICollection<Servicio> tblServicio { get; set; }
    }
}
