//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeisonAdarme.BLL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> IdEmpleado { get; set; }
        public Nullable<int> IdTipoServicio { get; set; }
        public Nullable<int> IdEstadoServicio { get; set; }
        public Nullable<System.DateTime> FechaPeticion { get; set; }
        public Nullable<System.DateTime> FechaTomado { get; set; }
        public Nullable<System.DateTime> FechaFinalizado { get; set; }
        public Nullable<int> NivelSatisfaccion { get; set; }
        public string CodigoServicio { get; set; }
        public Nullable<System.Guid> IdCliente { get; set; }
        public Nullable<System.Guid> IdEmpresa { get; set; }
    
        public virtual EstadoServicio mas_tblEstadoServicio { get; set; }
        public virtual Cliente tblCliente { get; set; }
        public virtual Empleado tblEmpleado { get; set; }
        public virtual Empresa tblEmpresa { get; set; }
        public virtual TipoServicio tblTipoServicio { get; set; }
    }
}
