//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeisonAdarme.BLL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioEmpleado
    {
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> IdEmpleado { get; set; }
        public Nullable<int> IdTipoServicio { get; set; }
        public Nullable<bool> EsActivo { get; set; }
    
        public virtual Empleado tblEmpleado { get; set; }
        public virtual TipoServicio tblTipoServicio { get; set; }
    }
}
