//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeisonAdarme.BLL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicio
    {
        public TipoServicio()
        {
            this.tblServicio = new HashSet<Servicio>();
            this.tblServicioEmpleado = new HashSet<ServicioEmpleado>();
        }
    
        public int IdTipoServicio { get; set; }
        public string NombreTipoServicio { get; set; }
        public Nullable<int> Complejidad { get; set; }
        public Nullable<int> TiempoEstimado { get; set; }
        public Nullable<bool> EsActivo { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.Guid> IdEmpresa { get; set; }
    
        public virtual Empresa tblEmpresa { get; set; }
        public virtual ICollection<Servicio> tblServicio { get; set; }
        public virtual ICollection<ServicioEmpleado> tblServicioEmpleado { get; set; }
    }
}
